// The Flutter SDK path comes from the module's own local.properties, which
// `flutter pub get` maintains. It is read twice because `pluginManagement` is evaluated
// in an isolated scope that cannot see top-level declarations, and it has to be the very
// first block in this file.
fun readFlutterSdk(dir: java.io.File): String {
    val f = java.io.File(dir, "ui/.android/local.properties")
    require(f.exists()) {
        "ui/.android/local.properties is missing. Run `flutter pub get` in ui/ first."
    }
    val props = java.util.Properties()
    f.inputStream().use { props.load(it) }
    return requireNotNull(props.getProperty("flutter.sdk")) {
        "flutter.sdk not set in ui/.android/local.properties"
    }
}

pluginManagement {
    val sdk = run {
        val f = java.io.File(rootDir, "ui/.android/local.properties")
        val props = java.util.Properties()
        f.inputStream().use { props.load(it) }
        props.getProperty("flutter.sdk")
    }
    includeBuild("$sdk/packages/flutter_tools/gradle")
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        maven("https://maven-central.storage-download.googleapis.com/maven2/")
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    // PREFER_SETTINGS, not the default PREFER_PROJECT and not FAIL_ON_PROJECT_REPOS.
    //
    // The Flutter Gradle plugin adds `download.flutter.io` to every project through
    // `allprojects`. Under PREFER_PROJECT that project repository *replaces* this list
    // for UNIQUE's own modules, and they can then only resolve Flutter engine artifacts -
    // kotlin-stdlib and androidx stop being findable. PREFER_SETTINGS keeps this list
    // authoritative; the Flutter engine repository is included below so nothing is lost.
    //
    // FAIL_ON_PROJECT_REPOS is not usable because the generated Flutter module is
    // regenerated by the Flutter tool and cannot be edited to remove its repositories.
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        // Google's Maven Central mirror is listed first: it is a different host from
        // repo.maven.apache.org and keeps builds working when the primary CDN throttles.
        maven("https://maven-central.storage-download.googleapis.com/maven2/")
        mavenCentral()
        // Flutter engine artifacts.
        maven("https://storage.googleapis.com/download.flutter.io")
    }
}

rootProject.name = "unique"

include(":app")
include(":core:common")
include(":core:hook")
include(":core:compat")
include(":core:diagnostics")
include(":core:vprofile")
include(":core:vstorage")
include(":core:vpm")
include(":core:vam")
include(":core:vprocess")
include(":core:vpermission")
include(":core:google")
include(":core:native")

// Flutter add-to-app, inlined rather than applying ui/.android/include_flutter.groovy:
// that script wants to configure pluginManagement itself, which Gradle only permits in
// the first block of this file. Doing it explicitly keeps both requirements satisfied.
val flutterSdkPath = readFlutterSdk(rootDir)
include(":flutter")
project(":flutter").projectDir = file("ui/.android/Flutter")
apply(from = "$flutterSdkPath/packages/flutter_tools/gradle/module_plugin_loader.gradle")
