import java.io.File

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
}

// ---------------------------------------------------------------------------------
// Stub component generation.
//
// Android does not let an app create processes, activities or providers at runtime:
// they exist only because the manifest declares them. UNIQUE therefore pre-declares a
// pool of placeholder components that virtual components are routed onto
// (ARCHITECTURE.md section 5.1).
//
// Generated rather than hand-written because the counts are configuration, and hand
// maintaining ~180 manifest entries plus their Kotlin classes is how these projects
// accumulate silent drift between the two.
// ---------------------------------------------------------------------------------
val vappProcessCount = rootProject.extra["vappProcessCount"] as Int
val stubActivitiesPerProcess = rootProject.extra["stubActivitiesPerProcess"] as Int
// One more than a guest may use: the last of each slot is reserved for cold
// broadcast delivery. See VirtualServiceRouter.COLD_BROADCAST_STUB_INDEX.
val STUB_SERVICES_PER_PROCESS = 7

val generatedManifestDir = layout.buildDirectory.dir("generated/unique/manifest")
val generatedSourceDir = layout.buildDirectory.dir("generated/unique/kotlin")

val generateStubs by tasks.registering {
    description = "Generates the virtual-app stub components and the merged host manifest."
    group = "unique"

    val template = layout.projectDirectory.file("src/main/AndroidManifest.template.xml")
    inputs.file(template)
    inputs.property("processes", vappProcessCount)
    inputs.property("activitiesPerProcess", stubActivitiesPerProcess)
    inputs.property("servicesPerProcess", STUB_SERVICES_PER_PROCESS)
    outputs.dir(generatedManifestDir)
    outputs.dir(generatedSourceDir)

    doLast {
        val manifestDir = generatedManifestDir.get().asFile.apply { mkdirs() }
        val srcDir = File(generatedSourceDir.get().asFile, "com/unique/stub").apply { mkdirs() }

        // Four launch modes x two task-affinity variants. The affinity variants are what
        // let two instances of the same app occupy separate entries in Recents instead of
        // stacking into one task.
        val launchModes = listOf("standard", "singleTop", "singleTask", "singleInstance")
        val affinities = stubActivitiesPerProcess / launchModes.size

        val components = StringBuilder()
        val sources = StringBuilder()

        sources.append(
            """
            |// GENERATED by :app:generateStubs. Do not edit.
            |package com.unique.stub
            |
            |import com.unique.app.runtime.StubActivityBase
            |import com.unique.app.runtime.StubServiceBase
            |import com.unique.app.runtime.StubProviderBase
            |import com.unique.app.runtime.StubJobServiceBase
            |
            """.trimMargin()
        )

        for (p in 0 until vappProcessCount) {
            val process = ":vapp$p"
            for (mIdx in launchModes.indices) {
                for (a in 0 until affinities) {
                    val name = "ActivityStub_p${p}_m${mIdx}_a$a"
                    components.append(
                        """
                        |        <activity
                        |            android:name="com.unique.stub.$name"
                        |            android:process="$process"
                        |            android:exported="false"
                        |            android:launchMode="${launchModes[mIdx]}"
                        |            android:taskAffinity="${'$'}{applicationId}.vapp$p.a$a"
                        |            android:configChanges="mcc|mnc|locale|touchscreen|keyboard|keyboardHidden|navigation|orientation|screenLayout|uiMode|screenSize|smallestScreenSize|layoutDirection|density|fontScale|fontWeightAdjustment"
                        |            android:theme="@style/Theme.Unique.Stub"
                        |            android:windowSoftInputMode="adjustResize"
                        |            android:resizeableActivity="true" />
                        |
                        """.trimMargin()
                    )
                    sources.append("\nclass $name : StubActivityBase($p)\n")
                }
            }
            // One stub per concurrently-running virtual service. CreateServiceData carries
            // only the stub's ServiceInfo, with nothing to say which virtual service it
            // stands for, so the stub identity *is* the mapping key.
            for (sIdx in 0 until STUB_SERVICES_PER_PROCESS) {
                components.append(
                    """
                    |        <service
                    |            android:name="com.unique.stub.ServiceStub_p${p}_s$sIdx"
                    |            android:process="$process"
                    |            android:exported="false"
                    |            android:foregroundServiceType="dataSync|mediaPlayback|mediaProjection|microphone|camera|location|connectedDevice|phoneCall|shortService|specialUse" />
                    |
                    """.trimMargin()
                )
                sources.append("\nclass ServiceStub_p${p}_s$sIdx : StubServiceBase($p)\n")
            }
            components.append(
                """
                |
                |        <service
                |            android:name="com.unique.stub.JobStub_p$p"
                |            android:process="$process"
                |            android:exported="false"
                |            android:permission="android.permission.BIND_JOB_SERVICE" />
                |
                |        <provider
                |            android:name="com.unique.stub.ProviderStub_p$p"
                |            android:process="$process"
                |            android:authorities="${'$'}{applicationId}.vprovider.$p"
                |            android:exported="false"
                |            android:grantUriPermissions="true" />
                |
                """.trimMargin()
            )
            sources.append(
                """
                |
                |class JobStub_p$p : StubJobServiceBase($p)
                |class ProviderStub_p$p : StubProviderBase($p)
                |
                """.trimMargin()
            )
        }

        File(srcDir, "GeneratedStubs.kt").writeText(sources.toString())

        val manifest = template.asFile.readText()
            .replace("<!-- GENERATED_STUBS -->", components.toString())
        require(!manifest.contains("<!-- GENERATED_STUBS -->")) {
            "manifest template lost its GENERATED_STUBS marker"
        }
        File(manifestDir, "AndroidManifest.xml").writeText(manifest)

        logger.lifecycle(
            "generateStubs: ${vappProcessCount} process slots, " +
                "${vappProcessCount * stubActivitiesPerProcess} activities, " +
                "${vappProcessCount * (STUB_SERVICES_PER_PROCESS + 2)} services/providers"
        )
    }
}

// ---------------------------------------------------------------------------------
// The probe APK travels inside the test APK.
//
// Pushing it to the device with `adb push` is not reliable: scoped storage stops the
// shell writing into another app's Android/data directory, and `pm clear` deletes that
// directory anyway. Carrying it as an asset of the instrumentation APK removes the
// question entirely - the suite has the file wherever it runs.
// ---------------------------------------------------------------------------------
val probeApk = layout.projectDirectory.file("../tools/testapp/build/probe.apk")
val stagedProbeDir = layout.buildDirectory.dir("generated/unique/androidTestAssets")

val stageProbeApk by tasks.registering {
    description = "Stages the probe APK as an asset of the instrumentation APK."
    group = "unique"

    // The probe's *sources* are the input, not the APK it builds into.
    //
    // With no declared inputs this task was permanently UP-TO-DATE after its first run,
    // so a changed probe was rebuilt by tools/testapp/build.sh and then never copied: the
    // suite kept running yesterday's probe while reporting on today's engine. That is the
    // worst kind of failure a test harness can have, because everything looks green.
    inputs.dir(rootProject.file("tools/testapp/src"))
        .withPathSensitivity(PathSensitivity.RELATIVE)
    inputs.file(rootProject.file("tools/testapp/AndroidManifest.xml"))
    inputs.file(rootProject.file("tools/testapp/build.sh"))
    inputs.file(rootProject.file("tools/testapp/build-split.sh"))
    inputs.file(rootProject.file("tools/testapp/build-next.sh"))
    inputs.dir(rootProject.file("tools/testapp/split"))
        .withPathSensitivity(PathSensitivity.RELATIVE)
    // The resource table is an input too. It is where the probe's *name* lives, which is
    // the whole point of it existing — `android:label="@string/app_name"` is what makes
    // the label-resolution path testable rather than a story.
    inputs.dir(rootProject.file("tools/testapp/res"))
        .withPathSensitivity(PathSensitivity.RELATIVE)
    outputs.dir(stagedProbeDir)

    doLast {
        // Built unconditionally rather than only when missing: an APK that exists but
        // predates the sources is exactly the stale artefact this task must not stage.
        providers.exec {
            commandLine("bash", rootProject.file("tools/testapp/build.sh").absolutePath)
        }.result.get().assertNormalExitValue()
        // The feature split, and the bumped-version base the update test needs. Separate
        // script because they are separate artefacts with their own manifests, not a
        // renamed copy of the base.
        providers.exec {
            commandLine("bash", rootProject.file("tools/testapp/build-split.sh").absolutePath)
        }.result.get().assertNormalExitValue()
        providers.exec {
            commandLine("bash", rootProject.file("tools/testapp/build-next.sh").absolutePath)
        }.result.get().assertNormalExitValue()

        val source = probeApk.asFile
        require(source.isFile) {
            "tools/testapp/build/probe.apk is missing. Run tools/testapp/build.sh."
        }
        val dest = stagedProbeDir.get().asFile.apply { mkdirs() }
        source.copyTo(File(dest, "probe.apk"), overwrite = true)
        for (extra in listOf("split_feature.apk", "probe-next.apk")) {
            val file = File(source.parentFile, extra)
            require(file.isFile) { "tools/testapp/build/$extra is missing." }
            file.copyTo(File(dest, extra), overwrite = true)
        }
        logger.lifecycle("stageProbeApk: ${source.length()} bytes + split + next")
    }
}

android {
    namespace = "com.unique.app"

    defaultConfig {
        applicationId = rootProject.extra["applicationId"] as String
        targetSdk = rootProject.extra["targetSdk"] as Int
        versionCode = rootProject.extra["uniqueVersionCode"] as Int
        versionName = rootProject.extra["uniqueVersionName"] as String
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    sourceSets {
        getByName("main") {
            manifest.srcFile(generatedManifestDir.map { it.file("AndroidManifest.xml") })
            kotlin.srcDir(generatedSourceDir)
        }
        getByName("androidTest") {
            kotlin.srcDir("src/androidTest/kotlin")
            assets.srcDir(stagedProbeDir)
        }
    }

    signingConfigs {
        // A release build that cannot be installed is not a deliverable, and one that
        // cannot install *over the last one* costs the tester every instance they had.
        //
        // This used to fall back to Android's own `~/.android/debug.keystore`, which each
        // machine generates for itself. Two builds made in two sessions therefore had two
        // different keys, and Android's error for that is the unhelpful `App not
        // installed`. The only way through it is to uninstall — which deletes the
        // instances, their data, and any expansion file the tester spent an evening
        // importing. That is a large price for a build-machine detail.
        //
        // So the key lives in the repository. It is a *test* key and is marked as one in
        // its own subject line: an APK signed this way must not be distributed, its
        // password is written here in the open, and anyone who has the repository can
        // produce a build that installs over this one. That is exactly what it is for.
        // Supply `uniqueKeystore` and friends for a real release.
        create("testSigned") {
            val supplied = providers.gradleProperty("uniqueKeystore").orNull
            if (supplied != null) {
                storeFile = file(supplied)
                storePassword = providers.gradleProperty("uniqueKeystorePassword").orNull
                keyAlias = providers.gradleProperty("uniqueKeyAlias").orNull
                keyPassword = providers.gradleProperty("uniqueKeyPassword").orNull
            } else {
                storeFile = file("debug.keystore")
                storePassword = "android"
                keyAlias = "androiddebugkey"
                keyPassword = "android"
            }
        }
    }

    buildTypes {
        // `DIAGNOSTIC_LOGCAT` decides whether UNIQUE's structured events are *also* written
        // to the system log, on top of the ring buffers the export reads.
        //
        // It is not `BuildConfig.DEBUG`, which is what this used to be, and the difference
        // cost a physical-device run: the build a tester installs is not debuggable, so
        // `DEBUG` was false, so a logcat capture from the phone contained only warnings and
        // errors — no `PROCESS_START`, no `BOOTSTRAP_OK`, no hook report, none of the trace
        // that says what happened before the failure. A tester recording with a logcat app
        // instead of `adb` is the whole point of the artifact; the build has to talk to it.
        debug {
            isMinifyEnabled = false
            buildConfigField("boolean", "DIAGNOSTIC_LOGCAT", "true")
        }
        // The build a physical-device tester actually gets.
        //
        // Everything about the *engine* is the debug build: no R8, so no keep rule can be
        // wrong, and the same classes the acceptance suite runs against. What differs is
        // Flutter, which builds its Dart code ahead of time here instead of shipping a JIT
        // kernel. That is not a detail: the debug APK is 77 MB, of which 40 MB is
        // `kernel_blob.bin` and 36 MB the debug engine, and 77 MB is the difference between
        // an artifact that can be handed to someone and one that cannot.
        //
        // Named `verify` rather than `profile` on purpose. Flutter's Gradle plugin picks
        // its Dart build mode from the build type: the name `profile` selects profile mode,
        // which ships a VM-service snapshot for DevTools to attach to; any other name with
        // `isDebuggable = false` selects release mode, which is what a tester wants and is
        // 1.6 MB smaller for a facility nobody here uses.
        //
        // `isDebuggable = false` also means ActivityManager gives this build the ordinary
        // ten-second process-start timeout rather than a debug build's twenty. That is the
        // budget a shipped app lives inside, so it is the right one to be measured against.
        create("verify") {
            initWith(getByName("debug"))
            isMinifyEnabled = false
            isDebuggable = false
            buildConfigField("boolean", "DIAGNOSTIC_LOGCAT", "true")
            signingConfig = signingConfigs.getByName("testSigned")
            matchingFallbacks += listOf("release", "debug")
        }
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            // Off in the shipped build. Every line still goes through the redactor
            // (§14.2), but the system log is readable by anything with a log reader and a
            // released app has no business filling it.
            buildConfigField("boolean", "DIAGNOSTIC_LOGCAT", "false")
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            // The instrumentation APK's own problems stay in its own file; see
            // proguard-test-rules.pro.
            testProguardFiles("proguard-test-rules.pro")
            signingConfig = signingConfigs.getByName("testSigned")
        }
    }

    // Which variant the acceptance suite runs against: `-PuniqueTestBuildType=verify`
    // points it at the build a tester is actually given, and `=release` at the minified
    // one. Both matter for the same reason — a build nobody ran the suite against is a
    // build nobody has checked, and for a virtualization engine, which is nearly all
    // reflection, that is exactly the build to be suspicious of.
    testBuildType = (providers.gradleProperty("uniqueTestBuildType").orNull ?: "debug")

    buildFeatures {
        buildConfig = true
    }

    packaging {
        jniLibs { useLegacyPackaging = false }
        resources { excludes += setOf("META-INF/*.version", "META-INF/*.kotlin_module") }
    }
}

// The generated manifest and sources must exist before anything reads them.
tasks.named("preBuild").configure { dependsOn(generateStubs) }
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
    dependsOn(generateStubs)
}
tasks.matching { it.name.contains("AndroidTestAssets") || it.name.contains("androidTestAssets") }
    .configureEach { dependsOn(stageProbeApk) }

dependencies {
    implementation(project(":core:common"))
    implementation(project(":core:hook"))
    implementation(project(":core:compat"))
    implementation(project(":core:diagnostics"))
    implementation(project(":core:native"))
    implementation(project(":core:vprofile"))
    implementation(project(":core:vstorage"))
    implementation(project(":core:vpm"))
    implementation(project(":core:vam"))
    implementation(project(":core:vprocess"))
    implementation(project(":core:vpermission"))
    implementation(project(":core:google"))

    implementation(project(":flutter"))

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.startup)
    implementation(libs.kotlinx.coroutines.android)

    // The on-device verification suite. It drives UniqueEngine, the same entry point the
    // interface uses, so the test cannot pass through a path the product does not take.
    androidTestImplementation(libs.androidx.test.core)
    androidTestImplementation(libs.androidx.test.runner)
    androidTestImplementation(libs.androidx.test.rules)
    androidTestImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.truth)
    androidTestImplementation(libs.kotlinx.coroutines.android)
    // AndroidJUnitRunner loads androidx.tracing.Trace in its own onCreate. It normally
    // arrives from the *app* APK, and in a minified build the app's R8 run removes it —
    // correctly, since the product never uses it — leaving the runner to look for a class
    // in an APK that no longer has it, and the whole suite to die before its first test:
    //
    //   NoClassDefFoundError: Failed resolution of: Landroidx/tracing/Trace;
    //       at androidx.test.runner.AndroidJUnitRunner.onCreate
    //
    // A -keep rule cannot fix that: the class is on R8's classpath for this variant, not
    // its program input. Declared here so the instrumentation APK carries its own copy and
    // does not depend on what the product happened to keep.
    androidTestImplementation("androidx.tracing:tracing:1.2.0")
}
