import java.io.File

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
}

// ---------------------------------------------------------------------------------
// Stub component generation.
//
// Android does not let an app create processes, activities or providers at runtime:
// they exist only because the manifest declares them. UNIQUE therefore pre-declares a
// pool of placeholder components that virtual components are routed onto
// (ARCHITECTURE.md section 5.1).
//
// Generated rather than hand-written because the counts are configuration, and hand
// maintaining ~180 manifest entries plus their Kotlin classes is how these projects
// accumulate silent drift between the two.
// ---------------------------------------------------------------------------------
val vappProcessCount = rootProject.extra["vappProcessCount"] as Int
val stubActivitiesPerProcess = rootProject.extra["stubActivitiesPerProcess"] as Int

val generatedManifestDir = layout.buildDirectory.dir("generated/unique/manifest")
val generatedSourceDir = layout.buildDirectory.dir("generated/unique/kotlin")

val generateStubs by tasks.registering {
    description = "Generates the virtual-app stub components and the merged host manifest."
    group = "unique"

    val template = layout.projectDirectory.file("src/main/AndroidManifest.template.xml")
    inputs.file(template)
    inputs.property("processes", vappProcessCount)
    inputs.property("activitiesPerProcess", stubActivitiesPerProcess)
    outputs.dir(generatedManifestDir)
    outputs.dir(generatedSourceDir)

    doLast {
        val manifestDir = generatedManifestDir.get().asFile.apply { mkdirs() }
        val srcDir = File(generatedSourceDir.get().asFile, "com/unique/stub").apply { mkdirs() }

        // Four launch modes x two task-affinity variants. The affinity variants are what
        // let two instances of the same app occupy separate entries in Recents instead of
        // stacking into one task.
        val launchModes = listOf("standard", "singleTop", "singleTask", "singleInstance")
        val affinities = stubActivitiesPerProcess / launchModes.size

        val components = StringBuilder()
        val sources = StringBuilder()

        sources.append(
            """
            |// GENERATED by :app:generateStubs. Do not edit.
            |package com.unique.stub
            |
            |import com.unique.app.runtime.StubActivityBase
            |import com.unique.app.runtime.StubServiceBase
            |import com.unique.app.runtime.StubProviderBase
            |import com.unique.app.runtime.StubJobServiceBase
            |
            """.trimMargin()
        )

        for (p in 0 until vappProcessCount) {
            val process = ":vapp$p"
            for (mIdx in launchModes.indices) {
                for (a in 0 until affinities) {
                    val name = "ActivityStub_p${p}_m${mIdx}_a$a"
                    components.append(
                        """
                        |        <activity
                        |            android:name="com.unique.stub.$name"
                        |            android:process="$process"
                        |            android:exported="false"
                        |            android:launchMode="${launchModes[mIdx]}"
                        |            android:taskAffinity="${'$'}{applicationId}.vapp$p.a$a"
                        |            android:configChanges="mcc|mnc|locale|touchscreen|keyboard|keyboardHidden|navigation|orientation|screenLayout|uiMode|screenSize|smallestScreenSize|layoutDirection|density|fontScale|fontWeightAdjustment"
                        |            android:theme="@style/Theme.Unique.Stub"
                        |            android:windowSoftInputMode="adjustResize"
                        |            android:resizeableActivity="true" />
                        |
                        """.trimMargin()
                    )
                    sources.append("\nclass $name : StubActivityBase($p)\n")
                }
            }
            components.append(
                """
                |        <service
                |            android:name="com.unique.stub.ServiceStub_p$p"
                |            android:process="$process"
                |            android:exported="false"
                |            android:foregroundServiceType="dataSync|mediaPlayback|mediaProjection|microphone|camera|location|connectedDevice|phoneCall|shortService|specialUse" />
                |
                |        <service
                |            android:name="com.unique.stub.JobStub_p$p"
                |            android:process="$process"
                |            android:exported="false"
                |            android:permission="android.permission.BIND_JOB_SERVICE" />
                |
                |        <provider
                |            android:name="com.unique.stub.ProviderStub_p$p"
                |            android:process="$process"
                |            android:authorities="${'$'}{applicationId}.vprovider.$p"
                |            android:exported="false"
                |            android:grantUriPermissions="true" />
                |
                """.trimMargin()
            )
            sources.append(
                """
                |
                |class ServiceStub_p$p : StubServiceBase($p)
                |class JobStub_p$p : StubJobServiceBase($p)
                |class ProviderStub_p$p : StubProviderBase($p)
                |
                """.trimMargin()
            )
        }

        File(srcDir, "GeneratedStubs.kt").writeText(sources.toString())

        val manifest = template.asFile.readText()
            .replace("<!-- GENERATED_STUBS -->", components.toString())
        require(!manifest.contains("<!-- GENERATED_STUBS -->")) {
            "manifest template lost its GENERATED_STUBS marker"
        }
        File(manifestDir, "AndroidManifest.xml").writeText(manifest)

        logger.lifecycle(
            "generateStubs: ${vappProcessCount} process slots, " +
                "${vappProcessCount * stubActivitiesPerProcess} activities, " +
                "${vappProcessCount * 3} services/providers"
        )
    }
}

android {
    namespace = "com.unique.app"

    defaultConfig {
        applicationId = rootProject.extra["applicationId"] as String
        targetSdk = rootProject.extra["targetSdk"] as Int
        versionCode = rootProject.extra["uniqueVersionCode"] as Int
        versionName = rootProject.extra["uniqueVersionName"] as String
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    sourceSets {
        getByName("main") {
            manifest.srcFile(generatedManifestDir.map { it.file("AndroidManifest.xml") })
            kotlin.srcDir(generatedSourceDir)
        }
        getByName("androidTest") { kotlin.srcDir("src/androidTest/kotlin") }
    }

    buildTypes {
        debug {
            isMinifyEnabled = false
        }
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }

    buildFeatures {
        buildConfig = true
    }

    packaging {
        jniLibs { useLegacyPackaging = false }
        resources { excludes += setOf("META-INF/*.version", "META-INF/*.kotlin_module") }
    }
}

// The generated manifest and sources must exist before anything reads them.
tasks.named("preBuild").configure { dependsOn(generateStubs) }
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
    dependsOn(generateStubs)
}

dependencies {
    implementation(project(":core:common"))
    implementation(project(":core:hook"))
    implementation(project(":core:compat"))
    implementation(project(":core:diagnostics"))
    implementation(project(":core:native"))
    implementation(project(":core:vprofile"))
    implementation(project(":core:vstorage"))
    implementation(project(":core:vpm"))
    implementation(project(":core:vam"))
    implementation(project(":core:vprocess"))
    implementation(project(":core:vpermission"))
    implementation(project(":core:google"))

    implementation(project(":flutter"))

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.startup)
    implementation(libs.kotlinx.coroutines.android)

    // The on-device verification suite. It drives UniqueEngine, the same entry point the
    // interface uses, so the test cannot pass through a path the product does not take.
    androidTestImplementation(libs.androidx.test.core)
    androidTestImplementation(libs.androidx.test.runner)
    androidTestImplementation(libs.androidx.test.rules)
    androidTestImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.truth)
    androidTestImplementation(libs.kotlinx.coroutines.android)
}
